### ISSUE TITLE
Directory or file not found

### ISSUE THREAD

**Issue by Bluefin33** [Str8UpWHITE64/Dead-Rising-TimeSkip-Steam-Deck#1]
Having copied the code like for like, upon launch in the terminal the code reads that I can't find the directory for proton, claiming it not to be there when it is indeed there in the proton 7 folder.. the text also appears red, with run in grey and the exe's in blue.. but no luck in figuring out how to fix it.

**Comment by Str8UpWHITE64** [comment]
That looks to be on me.  I believe I have left off the leading "/" in the file path for proton in the instructions.  I will update it in the instructions.

What it should be is:
`"/home/deck/.local/share/Steam/steamapps/common/Proton 7.0/proton" run DeadRising.exe & "/home/deck/.local/share/Steam/steamapps/common/Proton 7.0/proton" run DeadRisingSpeedrunningSkipTool.exe & "/home/deck/.local/share/Steam/steamapps/common/Proton 7.0/proton" run LiveSplit.exe`

**Comment by Bluefin33** [comment]
Oh right haha thanks for getting back to me I'll give it another go later with the correction and post how it goes!

**Comment by Str8UpWHITE64** [comment]
Awesome, let me know if it works!

**Comment by Bluefin33** [comment]
Sooo update.. that has moved thing along a little. Now I have the following.

Proton: No compat data path?
/home/deck/.local/share/Steam/steamapps/common/Dead Rising/script: line 4: Deadrising.exe: command not found.

Then the same again for DeadRisingSpeedrunningSkipTool.exe

Sorry I'm literally just a steam deck user, I don't know anything about coding or Linux.. I just love dead rising and want to speed run it on the go.. thanks for you help with this.

I won't be running the livesplit yet, so just typed the code as attached.
![PXL_20230404_165256857](https://user-images.githubusercontent.com/129803759/229863397-05744fad-44f9-4d38-89d5-24d6ac373592.jpg)

**Comment by Str8UpWHITE64** [comment]
Looks like you may be in the wrong folder with this file.  You should be in `/run/media/mmcblk0p1/steamapps/common/Dead\ Rising/`
